default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: mvp
  pool: 5
  timeout: 5000
  password: mysecretpassword


development:
  <<: *default
  database: pgs_trace_db_dev

test:
  <<: *default
  database: pgs_trace_db_test

production:
  <<: *default
  database: pgs_trace_db
